### ISSUE TITLE
RSBBSSession Awaits Possible Fix

### ISSUE THREAD

**Issue by Pairman** [xdlinux/libxduauth#17]
I was testing RSBBSSession (unchanged by me, just ``1.8.2`` fresh install) but it throws similar exceptions repeatedly:
```
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/libxduauth/sites/rsbbs.py", line 17, in __init__
    if not self.is_loggedin():
           ^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/libxduauth/sites/rsbbs.py", line 53, in is_loggedin
    return self.get(f'http://{self.HOST}/home.php', params={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/libxduauth/AuthSession.py", line 29, in request
    ret = super().request(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pairman/Downloads/venv/lib64/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rsbbs.xidian.edu.cn', port=80): Max retries exceeded with url: /home.php?mod=space&do=profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f584f6579e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I'm not around therefore only testing it via ssh on my server in the campus, so there's nothing more I can do. RSBBSSession needs inspection and probably fix. Thanks.

**Comment by frankli0324** [comment]
rsbbs site is closed indefinitely
